// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace LipstickDataAccess.MemberContext;

public partial class LipstickMemberDatabaseContext : DbContext
{
    public LipstickMemberDatabaseContext(DbContextOptions<LipstickMemberDatabaseContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TableFavorite> TableFavorites { get; set; }

    public virtual DbSet<TableGender> TableGenders { get; set; }

    public virtual DbSet<TableUser> TableUsers { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TableFavorite>(entity =>
        {
            entity.HasKey(e => new { e.ProductId, e.UserId });

            entity.ToTable("Table_Favorites");
        });

        modelBuilder.Entity<TableGender>(entity =>
        {
            entity.ToTable("Table_Genders");

            entity.Property(e => e.NameEn)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("NameEN");
            entity.Property(e => e.NameVn)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("NameVN");
        });

        modelBuilder.Entity<TableUser>(entity =>
        {
            entity.ToTable("Table_Users");

            entity.HasIndex(e => e.NormalizedEmail, "EmailIndex");

            entity.HasIndex(e => e.PhoneNumber, "IX_Table_Users_PhoneNumber").IsUnique();

            entity.HasIndex(e => e.NormalizedUserName, "UserNameIndex")
                .IsUnique()
                .HasFilter("([NormalizedUserName] IS NOT NULL)");

            entity.Property(e => e.Address).HasMaxLength(1000);
            entity.Property(e => e.Email).HasMaxLength(256);
            entity.Property(e => e.FullName).HasMaxLength(255);
            entity.Property(e => e.NormalizedEmail).HasMaxLength(256);
            entity.Property(e => e.NormalizedUserName).HasMaxLength(256);
            entity.Property(e => e.PhoneNumber).IsRequired();
            entity.Property(e => e.UserName).HasMaxLength(256);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}