// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SurveyDataAccess;

#nullable disable

namespace SurveyDataAccess.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20251112131915_InitDB")]
    partial class InitDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SurveyDataAccess.DTOs.AnswerDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("AnswerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuestionGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuestionTypeId")
                        .HasColumnType("int");

                    b.Property<byte?>("Rating")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.ToTable("Answers", (string)null);
                });

            modelBuilder.Entity("SurveyDataAccess.DTOs.ParticipantDTO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHighlighted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRejected")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReviewMode")
                        .HasColumnType("bit");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SurveyFormId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SurveyFormId");

                    b.ToTable("Participants", (string)null);
                });

            modelBuilder.Entity("SurveyDataAccess.DTOs.ParticipantInfoConfigDTO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldNameEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FieldNameVN")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<int>("MaxLength")
                        .HasColumnType("int");

                    b.Property<int>("MinLength")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceholderEN")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PlaceholderVN")
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("SurveyFormId")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SurveyFormId");

                    b.ToTable("ParticipantInfoConfigs", (string)null);
                });

            modelBuilder.Entity("SurveyDataAccess.DTOs.ParticipantInfoDTO", b =>
                {
                    b.Property<Guid>("ParticipantInfoConfigId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateValue")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NumberValue")
                        .HasColumnType("int");

                    b.Property<string>("TextValue")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("ParticipantInfoConfigId", "ParticipantId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("ParticipantInfos", (string)null);
                });

            modelBuilder.Entity("SurveyDataAccess.DTOs.PredefinedAnswerDTO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("NameEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NameVN")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte>("Priority")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("PredefinedAnswers", (string)null);
                });

            modelBuilder.Entity("SurveyDataAccess.DTOs.PredefinedAnswerLibraryDTO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("NameEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NameVN")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte>("Priority")
                        .HasColumnType("tinyint");

                    b.Property<int>("QuestionLibraryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionLibraryId");

                    b.ToTable("PredefinedAnswerLibraries", (string)null);
                });

            modelBuilder.Entity("SurveyDataAccess.DTOs.QuestionDTO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("NameEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NameVN")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<Guid?>("QuestionGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuestionTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("SurveyFormId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionGroupId");

                    b.HasIndex("QuestionTypeId");

                    b.HasIndex("SurveyFormId");

                    b.ToTable("Questions", (string)null);
                });

            modelBuilder.Entity("SurveyDataAccess.DTOs.QuestionGroupDTO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("NameEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NameVN")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte>("Priority")
                        .HasColumnType("tinyint");

                    b.Property<int>("SurveyFormId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SurveyFormId");

                    b.ToTable("QuestionGroups", (string)null);
                });

            modelBuilder.Entity("SurveyDataAccess.DTOs.QuestionGroupLibraryDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NameEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NameVN")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("QuestionGroupLibraries", (string)null);
                });

            modelBuilder.Entity("SurveyDataAccess.DTOs.QuestionLibraryDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NameEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NameVN")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("QuestionGroupLibraryId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionGroupLibraryId");

                    b.HasIndex("QuestionTypeId");

                    b.ToTable("QuestionLibraries", (string)null);
                });

            modelBuilder.Entity("SurveyDataAccess.DTOs.QuestionTypeDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("QuestionTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 12, 20, 19, 15, 211, DateTimeKind.Local).AddTicks(3021),
                            IsActive = true,
                            Name = "Câu hỏi đóng",
                            Note = "Câu hỏi đóng (Closed-ended question) – Chỉ có các câu trả lời sẵn."
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 12, 20, 19, 15, 211, DateTimeKind.Local).AddTicks(4107),
                            IsActive = true,
                            Name = "Câu hỏi mở",
                            Note = "Câu hỏi mở (Open-ended question) – Người dùng nhập câu trả lời."
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 11, 12, 20, 19, 15, 211, DateTimeKind.Local).AddTicks(4112),
                            IsActive = true,
                            Name = "Câu hỏi kết hợp",
                            Note = "Câu hỏi kết hợp (Hybrid question) hoặc Câu hỏi mở rộng (Extended question) – Vừa có câu trả lời sẵn, vừa cho phép người dùng nhập câu trả lời riêng."
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 11, 12, 20, 19, 15, 211, DateTimeKind.Local).AddTicks(4113),
                            IsActive = true,
                            Name = "Câu hỏi nhiều lựa chọn",
                            Note = "Cho phép chọn nhiều đáp án cùng lúc. (MultipleChoiceQuestion)"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 11, 12, 20, 19, 15, 211, DateTimeKind.Local).AddTicks(4114),
                            IsActive = true,
                            Name = "Câu hỏi đánh giá",
                            Note = "Cẩu hỏi đáng giá (RatingQuestion) - Cho người dùng đánh giá mức độ trên 5 sao."
                        });
                });

            modelBuilder.Entity("SurveyDataAccess.DTOs.StoreDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Representative")
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Stores", (string)null);
                });

            modelBuilder.Entity("SurveyDataAccess.DTOs.SurveyFormDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DescriptionEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DescriptionVN")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FormStyleId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLimited")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StoreId")
                        .HasColumnType("int");

                    b.Property<string>("TitleEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TitleVN")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("SurveyForms", (string)null);
                });

            modelBuilder.Entity("SurveyDataAccess.DTOs.AnswerDTO", b =>
                {
                    b.HasOne("SurveyDataAccess.DTOs.ParticipantDTO", "Participant")
                        .WithMany("Answers")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("SurveyDataAccess.DTOs.ParticipantDTO", b =>
                {
                    b.HasOne("SurveyDataAccess.DTOs.SurveyFormDTO", "SurveyForm")
                        .WithMany("Participants")
                        .HasForeignKey("SurveyFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SurveyForm");
                });

            modelBuilder.Entity("SurveyDataAccess.DTOs.ParticipantInfoConfigDTO", b =>
                {
                    b.HasOne("SurveyDataAccess.DTOs.SurveyFormDTO", "SurveyForm")
                        .WithMany("ParticipantInfoConfigs")
                        .HasForeignKey("SurveyFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SurveyForm");
                });

            modelBuilder.Entity("SurveyDataAccess.DTOs.ParticipantInfoDTO", b =>
                {
                    b.HasOne("SurveyDataAccess.DTOs.ParticipantDTO", "Participant")
                        .WithMany("ParticipantInfos")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("SurveyDataAccess.DTOs.PredefinedAnswerDTO", b =>
                {
                    b.HasOne("SurveyDataAccess.DTOs.QuestionDTO", "Question")
                        .WithMany("PredefinedAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("SurveyDataAccess.DTOs.PredefinedAnswerLibraryDTO", b =>
                {
                    b.HasOne("SurveyDataAccess.DTOs.QuestionLibraryDTO", "Question")
                        .WithMany("PredefinedAnswerLibraries")
                        .HasForeignKey("QuestionLibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("SurveyDataAccess.DTOs.QuestionDTO", b =>
                {
                    b.HasOne("SurveyDataAccess.DTOs.QuestionGroupDTO", "QuestionGroup")
                        .WithMany("Questions")
                        .HasForeignKey("QuestionGroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SurveyDataAccess.DTOs.QuestionTypeDTO", "QuestionType")
                        .WithMany()
                        .HasForeignKey("QuestionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SurveyDataAccess.DTOs.SurveyFormDTO", "SurveyForm")
                        .WithMany("Questions")
                        .HasForeignKey("SurveyFormId");

                    b.Navigation("QuestionGroup");

                    b.Navigation("QuestionType");

                    b.Navigation("SurveyForm");
                });

            modelBuilder.Entity("SurveyDataAccess.DTOs.QuestionGroupDTO", b =>
                {
                    b.HasOne("SurveyDataAccess.DTOs.SurveyFormDTO", "SurveyForm")
                        .WithMany("QuestionGroups")
                        .HasForeignKey("SurveyFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SurveyForm");
                });

            modelBuilder.Entity("SurveyDataAccess.DTOs.QuestionLibraryDTO", b =>
                {
                    b.HasOne("SurveyDataAccess.DTOs.QuestionGroupLibraryDTO", "QuestionGroupLibrary")
                        .WithMany("QuestionLibraries")
                        .HasForeignKey("QuestionGroupLibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SurveyDataAccess.DTOs.QuestionTypeDTO", "QuestionType")
                        .WithMany("Questions")
                        .HasForeignKey("QuestionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionGroupLibrary");

                    b.Navigation("QuestionType");
                });

            modelBuilder.Entity("SurveyDataAccess.DTOs.ParticipantDTO", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("ParticipantInfos");
                });

            modelBuilder.Entity("SurveyDataAccess.DTOs.QuestionDTO", b =>
                {
                    b.Navigation("PredefinedAnswers");
                });

            modelBuilder.Entity("SurveyDataAccess.DTOs.QuestionGroupDTO", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("SurveyDataAccess.DTOs.QuestionGroupLibraryDTO", b =>
                {
                    b.Navigation("QuestionLibraries");
                });

            modelBuilder.Entity("SurveyDataAccess.DTOs.QuestionLibraryDTO", b =>
                {
                    b.Navigation("PredefinedAnswerLibraries");
                });

            modelBuilder.Entity("SurveyDataAccess.DTOs.QuestionTypeDTO", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("SurveyDataAccess.DTOs.SurveyFormDTO", b =>
                {
                    b.Navigation("ParticipantInfoConfigs");

                    b.Navigation("Participants");

                    b.Navigation("QuestionGroups");

                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
