// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SurveyDataAccess;

#nullable disable

namespace SurveyDataAccess.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20250923021458_InitialDB")]
    partial class InitialDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SurveyDataAccess.DTOs.AnswerDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("AnswerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuestionGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuestionTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte?>("Rating")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.ToTable("Table_Answers", (string)null);
                });

            modelBuilder.Entity("SurveyDataAccess.DTOs.ParticipantDTO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("varchar(10)");

                    b.Property<int>("SurveyFormId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SurveyFormId");

                    b.ToTable("Table_Participants", (string)null);
                });

            modelBuilder.Entity("SurveyDataAccess.DTOs.PredefinedAnswerDTO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("NameEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NameVN")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Table_PredefinedAnswers", (string)null);
                });

            modelBuilder.Entity("SurveyDataAccess.DTOs.PredefinedAnswerLibraryDTO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("NameEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NameVN")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("QuestionLibraryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionLibraryId");

                    b.ToTable("Table_PredefinedAnswerLibraries", (string)null);
                });

            modelBuilder.Entity("SurveyDataAccess.DTOs.QuestionDTO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("NameEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NameVN")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("QuestionGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuestionTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("SurveyFormId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionGroupId");

                    b.HasIndex("QuestionTypeId");

                    b.HasIndex("SurveyFormId");

                    b.ToTable("Table_Questions", (string)null);
                });

            modelBuilder.Entity("SurveyDataAccess.DTOs.QuestionGroupDTO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("NameEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NameVN")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte>("Priority")
                        .HasColumnType("tinyint");

                    b.Property<int>("SurveyFormId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SurveyFormId");

                    b.ToTable("Table_QuestionGroups", (string)null);
                });

            modelBuilder.Entity("SurveyDataAccess.DTOs.QuestionGroupLibraryDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NameEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NameVN")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte>("Priority")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Table_QuestionGroupLibraries", (string)null);
                });

            modelBuilder.Entity("SurveyDataAccess.DTOs.QuestionLibraryDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NameEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NameVN")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("QuestionGroupLibraryId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionGroupLibraryId");

                    b.HasIndex("QuestionTypeId");

                    b.ToTable("Table_QuestionLibraries", (string)null);
                });

            modelBuilder.Entity("SurveyDataAccess.DTOs.QuestionTypeDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Table_QuestionTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 23, 9, 14, 57, 963, DateTimeKind.Local).AddTicks(7644),
                            IsActive = true,
                            Name = "Câu hỏi đóng",
                            Note = "Câu hỏi đóng (Closed-ended question) – Chỉ có các câu trả lời sẵn."
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 9, 23, 9, 14, 57, 963, DateTimeKind.Local).AddTicks(9027),
                            IsActive = true,
                            Name = "Câu hỏi mở",
                            Note = "Câu hỏi mở (Open-ended question) – Người dùng nhập câu trả lời."
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 9, 23, 9, 14, 57, 963, DateTimeKind.Local).AddTicks(9034),
                            IsActive = true,
                            Name = "Câu hỏi kết hợp",
                            Note = "Câu hỏi kết hợp (Hybrid question) hoặc Câu hỏi mở rộng (Extended question) – Vừa có câu trả lời sẵn, vừa cho phép người dùng nhập câu trả lời riêng."
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 9, 23, 9, 14, 57, 963, DateTimeKind.Local).AddTicks(9035),
                            IsActive = true,
                            Name = "Câu hỏi nhiều lựa chọn",
                            Note = "Cho phép chọn nhiều đáp án cùng lúc. (MultipleChoiceQuestion)"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 9, 23, 9, 14, 57, 963, DateTimeKind.Local).AddTicks(9036),
                            IsActive = true,
                            Name = "Câu hỏi đánh giá",
                            Note = "Cẩu hỏi đáng giá (RatingQuestion) - Cho người dùng đánh giá mức độ trên 5 sao."
                        });
                });

            modelBuilder.Entity("SurveyDataAccess.DTOs.SurveyFormDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DescriptionEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DescriptionVN")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TitleEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TitleVN")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Table_SurveyForms", (string)null);
                });

            modelBuilder.Entity("SurveyDataAccess.DTOs.AnswerDTO", b =>
                {
                    b.HasOne("SurveyDataAccess.DTOs.ParticipantDTO", "Participant")
                        .WithMany("Answers")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("SurveyDataAccess.DTOs.ParticipantDTO", b =>
                {
                    b.HasOne("SurveyDataAccess.DTOs.SurveyFormDTO", "SurveyForm")
                        .WithMany("Participants")
                        .HasForeignKey("SurveyFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SurveyForm");
                });

            modelBuilder.Entity("SurveyDataAccess.DTOs.PredefinedAnswerDTO", b =>
                {
                    b.HasOne("SurveyDataAccess.DTOs.QuestionDTO", "Question")
                        .WithMany("PredefinedAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("SurveyDataAccess.DTOs.PredefinedAnswerLibraryDTO", b =>
                {
                    b.HasOne("SurveyDataAccess.DTOs.QuestionLibraryDTO", "Question")
                        .WithMany("PredefinedAnswerLibraries")
                        .HasForeignKey("QuestionLibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("SurveyDataAccess.DTOs.QuestionDTO", b =>
                {
                    b.HasOne("SurveyDataAccess.DTOs.QuestionGroupDTO", "QuestionGroup")
                        .WithMany("Questions")
                        .HasForeignKey("QuestionGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SurveyDataAccess.DTOs.QuestionTypeDTO", "QuestionType")
                        .WithMany()
                        .HasForeignKey("QuestionTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SurveyDataAccess.DTOs.SurveyFormDTO", "SurveyForm")
                        .WithMany("Questions")
                        .HasForeignKey("SurveyFormId");

                    b.Navigation("QuestionGroup");

                    b.Navigation("QuestionType");

                    b.Navigation("SurveyForm");
                });

            modelBuilder.Entity("SurveyDataAccess.DTOs.QuestionGroupDTO", b =>
                {
                    b.HasOne("SurveyDataAccess.DTOs.SurveyFormDTO", "SurveyForm")
                        .WithMany("QuestionGroups")
                        .HasForeignKey("SurveyFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SurveyForm");
                });

            modelBuilder.Entity("SurveyDataAccess.DTOs.QuestionLibraryDTO", b =>
                {
                    b.HasOne("SurveyDataAccess.DTOs.QuestionGroupLibraryDTO", "QuestionGroupLibrary")
                        .WithMany("QuestionLibraries")
                        .HasForeignKey("QuestionGroupLibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SurveyDataAccess.DTOs.QuestionTypeDTO", "QuestionType")
                        .WithMany("Questions")
                        .HasForeignKey("QuestionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionGroupLibrary");

                    b.Navigation("QuestionType");
                });

            modelBuilder.Entity("SurveyDataAccess.DTOs.ParticipantDTO", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("SurveyDataAccess.DTOs.QuestionDTO", b =>
                {
                    b.Navigation("PredefinedAnswers");
                });

            modelBuilder.Entity("SurveyDataAccess.DTOs.QuestionGroupDTO", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("SurveyDataAccess.DTOs.QuestionGroupLibraryDTO", b =>
                {
                    b.Navigation("QuestionLibraries");
                });

            modelBuilder.Entity("SurveyDataAccess.DTOs.QuestionLibraryDTO", b =>
                {
                    b.Navigation("PredefinedAnswerLibraries");
                });

            modelBuilder.Entity("SurveyDataAccess.DTOs.QuestionTypeDTO", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("SurveyDataAccess.DTOs.SurveyFormDTO", b =>
                {
                    b.Navigation("Participants");

                    b.Navigation("QuestionGroups");

                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
