using LipstickDataAccess.DTOs;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace LipstickDataAccess.Configurations
{
    public class OrderConfiguration : IEntityTypeConfiguration<OrderDTO>
    {
        public void Configure(EntityTypeBuilder<OrderDTO> builder)
        {
            builder.ToTable("Table_Orders");
            // Pseudocode:
            // 1. Change the Id property in OrderDTO to type Guid.
            // 2. In the configuration, set the Id property as the key and configure it to have a default value generated by the database (NEWSEQUENTIALID or NEWID).
            // 3. Mark the property as ValueGeneratedOnAdd.

            // Code:
            builder.HasKey(s => s.Id);
            builder.Property(s => s.Id)
                .HasDefaultValueSql("NEWSEQUENTIALID()")
                .ValueGeneratedOnAdd();
            builder.Property(s => s.Code).IsRequired().HasMaxLength(50);
            builder.HasIndex(s => s.Code).IsUnique();
            builder.Property(s => s.FullName).IsRequired().HasMaxLength(100);
            builder.Property(s => s.PhoneNumber).IsRequired().HasMaxLength(10);
        }
    }
}
